const { AUTHENTICATING, AUTHENTICATION_SUCCESSFULL, AUTHENTICATION_FAILED } = require("store/types/isAuthenticated");

const IS_AUTHENTICATING = () => ({
    type : AUTHENTICATING
});

const IS_AUTHENTICATED = () => ({
    type : AUTHENTICATION_SUCCESSFULL
})

const FAILED_TO_AUTHENTICATE = error => ({
    type : AUTHENTICATION_FAILED,
    payload: error 
})

export { IS_AUTHENTICATING, IS_AUTHENTICATED, FAILED_TO_AUTHENTICATE }