CREATE DATABASE nike;

CREATE TABLE product(
    _id SERIAL PRIMARY KEY NOT NULL,
    catagory VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    tagname VARCHAR(150) NOT NULL,
    price MONEY NOT NULL,
    description TEXT NOT NULL,
    gender VARCHAR(20) DEFAULT 'unisex',
    cover TEXT NOT NULL,
    otherimages TEXT[3] NOT NULL,
    admin VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE public.user(
    _id SERIAL PRIMARY KEY NOT NULL,
    img TEXT NOT NULL,
    fullname VARCHAR(200) NOT NULL,
    username VARCHAR(20) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP 
);