export const AUTHENTICATION_SUCCESSFULL = 'AUTHENTICATION_SUCCESSFULL';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const AUTHENTICATING = 'AUTHENTICATING';
export const USER_IS_AUTHENTICATED = 'USER_IS_AUTHENTICATED' 