POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "fullname" : "Sayantan",
    "username" : "icegeek_07",
    "email" : "sssamanta789@gmail.com",
    "password" : "sayaN1ssds",
    "confirmpassword" : "sayaN1ssds"
}

###
POST http://localhost:5000/auth/login


###
POST http://localhost:5000/auth/logout


###
GET http://localhost:5000/api/products

###
POST http://localhost:5000/api/products
Content-Type: application/json

{
    "catagory" : "clothing",
    "name" : "Nike Jordan",
    "tagname" : "AJ4 Graphic",
    "price" : 4295,
    "description" : "The Jordan AJ4 Graphic Fleece Pullover Hoodie uses a midweight French terry that's softly brushed on the inside. Bold colour-blocking and graphics, plus a toggle on the hood drawcord drive distinction.",
    "gender" : "male",
    "cover" : "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/40a19cdc-f195-437d-ab54-c8c93479e35e/jordan-aj4-graphic-fleece-pullover-hoodie-9JhxcD.png",
    "otherimages" : [
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/32996740-baeb-490a-8b30-c4478001229f/jordan-aj4-graphic-fleece-pullover-hoodie-9JhxcD.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/370440db-0f8a-4b7f-b439-151e6e8dfc3a/jordan-aj4-graphic-fleece-pullover-hoodie-9JhxcD.png",
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/f2e9ce17-9602-4b1c-8498-20e13c16213b/jordan-aj4-graphic-fleece-pullover-hoodie-9JhxcD.png"
    ],
    "admin" : "nikemin@ac.in"
}
